### ISSUE TITLE
go2还没出来，你这书皮都设计出来了

### ISSUE THREAD

**Issue by rfyiamcool** [chai2010/go2-book#3]
😅，这是要抢占市场呀，👍

**Comment by chai2010** [comment]
就像模块特性，只要设计有了，实现肯定就不远了。而且模块化还没有发布，很多人已经提前用起来了。
要抓好提前量，这样等Go2正式发布，就不需要从头再学习了 :)

**Comment by rfyiamcool** [comment]
可以可以
